[project]
name = "life-game-v1-1-copy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "customtkinter>=5.2.2",
    "matplotlib>=3.10.8",
    "pandas>=3.0.1",
    "pyinstaller>=6.19.0",
]
